### ISSUE TITLE
"Content Assist" did not complete normally

### ISSUE THREAD

**Issue by ccancinos** [ccancinos/rinzo-xml-editor#8]
I have a problem with content assist based on a XML schema. When I open a XML file with a specific XML schema for the first time I got the following error when I try to use content assist :

```
java.lang.NullPointerException
    at ar.com.tadp.xml.rinzo.core.contentassist.processors.XMLContentAssistProcessor.addAttributeProposals(XMLContentAssistProcessor.java:49)
    at ar.com.tadp.xml.rinzo.core.contentassist.processors.CompositeXMLContentAssistProcessor.addAttributeProposals(CompositeXMLContentAssistProcessor.java:133)
    at ar.com.tadp.xml.rinzo.core.contentassist.processors.CompositeXMLContentAssistProcessor.computeCompletionProposal(CompositeXMLContentAssistProcessor.java:85)
    at ar.com.tadp.xml.rinzo.core.contentassist.processors.CompositeXMLContentAssistProcessor.computeCompletionProposals(CompositeXMLContentAssistProcessor.java:67)
    at ar.com.tadp.xml.rinzo.core.contentassist.processors.CompositeContentAssistProcessor.computeCompletionProposals(CompositeContentAssistProcessor.java:52)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1830)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:556)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:553)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:488)
```

If I open a new file with the same XML schema, the content assist works just fine.
Also, when I launch Eclipse I've got the following stack trace :

```
java.io.FileNotFoundException: C:\Developpement\runtime-EclipseApplication\.metadata\.plugins\ar.com.tadp.xml.rinzo.core\.cache\f7.xsd (Le fichier spécifié est introuvable)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at org.eclipse.emf.ecore.resource.impl.URIConverterImpl.createFileInputStream(URIConverterImpl.java:462)
    at org.eclipse.emf.ecore.resource.impl.URIConverterImpl.createInputStream(URIConverterImpl.java:424)
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.getSchema(XSDTagDefinitionProvider.java:225)
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.updateDefinition(XSDTagDefinitionProvider.java:119)
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.<init>(XSDTagDefinitionProvider.java:76)
    at ar.com.tadp.xml.rinzo.core.RinzoXMLEditor.getCompositeSchemaTagContainersRegistry(RinzoXMLEditor.java:331)
    at ar.com.tadp.xml.rinzo.core.RinzoXMLEditor.getTagContainersRegistry(RinzoXMLEditor.java:300)
    at ar.com.tadp.xml.rinzo.core.EditorUpdater.run(EditorUpdater.java:56)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
java.lang.NullPointerException
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.parseElementsFrom(XSDTagDefinitionProvider.java:124)
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.updateDefinition(XSDTagDefinitionProvider.java:119)
    at ar.com.tadp.xml.rinzo.core.model.tags.xsd.XSDTagDefinitionProvider.<init>(XSDTagDefinitionProvider.java:76)
    at ar.com.tadp.xml.rinzo.core.RinzoXMLEditor.getCompositeSchemaTagContainersRegistry(RinzoXMLEditor.java:331)
    at ar.com.tadp.xml.rinzo.core.RinzoXMLEditor.getTagContainersRegistry(RinzoXMLEditor.java:300)
    at ar.com.tadp.xml.rinzo.core.EditorUpdater.run(EditorUpdater.java:56)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

but the XML schema appears in the cache directory few seconds later.
I tried to create my own editor extending the RinzoXMLEditor but I couldn't find how to solve this issue.
Do you have an idea of where this problem could come from ?
Thanks,
Arthur

**Comment by ccancinos** [comment]
Apparently this issue has been resolve in commit 5f99cbea2fe37093bc5e2d05ae52401308624f22
